- id: check-tcex-version
  always_run: true
  description: Check that TCEX version is up to date
  entry: check-tcex-version
  files: 'README.md'
  language: python
  name: Check TCEX version
  pass_filenames: false
